/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#include "PluginProcessor.h"
#include "PluginEditor.h"


//==============================================================================
HighFrequencyToneControlAudioProcessorEditor::HighFrequencyToneControlAudioProcessorEditor (HighFrequencyToneControlAudioProcessor& p)
    : AudioProcessorEditor (&p), processor (p)
{
    guiComponent.setProcessor(&processor);
    addAndMakeVisible(&guiComponent);
    // Make sure that before the constructor has finished, you've set the
    // editor's size to whatever you need it to be.
    setSize (400, 300);
}

HighFrequencyToneControlAudioProcessorEditor::~HighFrequencyToneControlAudioProcessorEditor()
{
}

//==============================================================================
void HighFrequencyToneControlAudioProcessorEditor::paint (Graphics& g)
{
    g.fillAll (Colours::white);

    g.setColour (Colours::black);
    g.setFont (15.0f);
    g.drawFittedText ("Hello World! Deepak", getLocalBounds(), Justification::centred, 1);
}

void HighFrequencyToneControlAudioProcessorEditor::resized()
{
    // This is generally where you'll want to lay out the positions of any
    // subcomponents in your editor..
    //guiComponent.setB
}
