/*
  ==============================================================================

    This file was auto-generated by the Introjucer!

    It contains the basic framework code for a JUCE plugin editor.

  ==============================================================================
*/

#ifndef PLUGINEDITOR_H_INCLUDED
#define PLUGINEDITOR_H_INCLUDED

#include "../JuceLibraryCode/JuceHeader.h"
#include "PluginProcessor.h"
#include "HighFrequencyToneControlComponent.h"


//==============================================================================
/**
*/
class HighFrequencyToneControlAudioProcessorEditor  : public AudioProcessorEditor
{
public:
    HighFrequencyToneControlAudioProcessorEditor (HighFrequencyToneControlAudioProcessor&);
    ~HighFrequencyToneControlAudioProcessorEditor();

    //==============================================================================
    void paint (Graphics&) override;
    void resized() override;

private:
    HighFrequencyToneControlComponent guiComponent;
    // This reference is provided as a quick way for your editor to
    // access the processor object that created it.
    HighFrequencyToneControlAudioProcessor& processor;

    JUCE_DECLARE_NON_COPYABLE_WITH_LEAK_DETECTOR (HighFrequencyToneControlAudioProcessorEditor)
};


#endif  // PLUGINEDITOR_H_INCLUDED
